#crop_query_data

if(print_tags == 1){
  print("CreateInputsSubs/NASSpull/crop_query_data.R")
}

# harvest and production data for
# (1) corn grain, (need 'CORN, GRAIN - ACRES HARVESTED', 'CORN, GRAIN - PRODUCTION, MEASURED IN BU')
# (2) corn silage, (need 'CORN, SILAGE - ACRES HARVESTED', 'CORN, SILAGE - PRODUCTION, MEASURED IN TONS')
# (3) wheat, (need 'WHEAT - ACRES HARVESTED', 'WHEAT - PRODUCTION, MEASURED IN BU')
# (4) oats, (need 'OATS - ACRES HARVESTED', 'OATS - PRODUCTION, MEASURED IN BU')
# (5) barley, (need 'BARLEY - ACRES HARVESTED', 'BARLEY - PRODUCTION, MEASURED IN BU')
# (6) sorghum grain, (need 'SORGHUM, GRAIN - ACRES HARVESTED', 'SORGHUM, GRAIN - PRODUCTION, MEASURED IN BU')
# (7) sorghum silage, (need 'SORGHUM, SILAGE - ACRES HARVESTED', 'SORGHUM, SILAGE - PRODUCTION, MEASURED IN TONS')
# (8) potatoes, (need 'POTATOES - ACRES HARVESTED', 'POTATOES - PRODUCTION, MEASURED IN CWT')
# (9) rye, (need 'RYE - ACRES HARVESTED', 'RYE - PRODUCTION, MEASURED IN BU')
# (10) alfalfa hay, (need 'HAY, ALFALFA - ACRES HARVESTED', 'HAY, ALFALFA - PRODUCTION, MEASURED IN TONS')
# (11) other hay, ('HAY - ACRES HARVESTED','HAY - PRODUCTION, MEASURED IN TONS')
# (12) soybeans, ('SOYBEANS - ACRES HARVESTED', 'SOYBEANS - PRODUCTION, MEASURED IN BU')
# (13) cropland, ('ag land, pastureland - acres' - ('ag land, pastureland, (excl cropland & woodland) - acres' + 'ag land, woodland - acres'))
# (14) noncropland, ('ag land, pastureland, (excl cropland & woodland) - acres' + 'ag land, woodland - acres')
# (15) rice, ('RICE - ACRES HARVESTED', 'RICE - PRODUCTION, MEASURED IN CWT')
# (16) peanuts ('PEANUTS - ACRES HARVESTED','PEANUTS - PRODUCTION, MEASURED IN LB')


crop_desc <- c(
  'CORN, GRAIN - ACRES HARVESTED',
  'CORN, GRAIN - PRODUCTION, MEASURED IN BU',
  'CORN, SILAGE - ACRES HARVESTED',
  'CORN, SILAGE - PRODUCTION, MEASURED IN TONS',
  'WHEAT - ACRES HARVESTED',
  'WHEAT - PRODUCTION, MEASURED IN BU',
  'OATS - ACRES HARVESTED',
  'OATS - PRODUCTION, MEASURED IN BU',
  'BARLEY - ACRES HARVESTED',
  'BARLEY - PRODUCTION, MEASURED IN BU',
  'SORGHUM, GRAIN - ACRES HARVESTED',
  'SORGHUM, GRAIN - PRODUCTION, MEASURED IN BU',
  'SORGHUM, SILAGE - ACRES HARVESTED',
  'SORGHUM, SILAGE - PRODUCTION, MEASURED IN TONS',
  'POTATOES - ACRES HARVESTED',
  'POTATOES - PRODUCTION, MEASURED IN CWT',
  'RYE - ACRES HARVESTED',
  'RYE - PRODUCTION, MEASURED IN BU',
  'HAY, ALFALFA - ACRES HARVESTED',
  'HAY, ALFALFA - PRODUCTION, MEASURED IN TONS',
  'HAY - ACRES HARVESTED',
  'HAY - PRODUCTION, MEASURED IN TONS',
  'SOYBEANS - ACRES HARVESTED',
  'SOYBEANS - PRODUCTION, MEASURED IN BU',
  'ag land, cropland, pastured only - acres',
  'ag land, pastureland - acres',
  'RICE - ACRES HARVESTED',
  'RICE - PRODUCTION, MEASURED IN CWT',
  'PEANUTS - ACRES HARVESTED',
  'PEANUTS - PRODUCTION, MEASURED IN LB'
)
